name: azure-blob

on:
  workflow_dispatch:
    inputs:
      container_name:
        description: Azure Blob storage container name
        required: true
        default: aiida-s3-test-container

jobs:

  tests:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: pip
        cache-dependency-path: pyproject.toml

    - name: Install Python package and dependencies
      run: pip install -e .[tests]

    - name: Run pytest
      env:
        AIIDA_S3_MOCK_AZURE_BLOB: false
        AIIDA_S3_AZURE_BLOB_CONNECTION_STRING: ${{ secrets.AZURE_BLOB_CONNECTION_STRING }}
        AIIDA_S3_AZURE_BLOB_CONTAINER_NAME: ${{ github.event.inputs.container_name }}
      run: pytest -sv tests
