name: ci

on: [push, pull_request]

jobs:

    pre-commit:

        runs-on: ubuntu-latest

        steps:
        -   uses: actions/checkout@v2

        -   name: Cache Python dependencies
            id: cache-pip
            uses: actions/cache@v1
            with:
                path: ~/.cache/pip
                key: pip-pre-commit-${{ hashFiles('**/setup.json') }}
                restore-keys:
                    pip-pre-commit-

        -   name: Install Python
            uses: actions/setup-python@v2
            with:
                python-version: '3.10'

        -   name: Install Python package and dependencies
            run: pip install -e .[pre-commit,tests]

        -   name: Install custom `aiida-core` branch
            run: pip install git+https://github.com/sphuber/aiida-core.git@feature/5495/storage-backend-entry-points

        -   name: Run pre-commit
            run: pre-commit run --all-files || ( git status --short ; git diff ; exit 1 )

    tests:

        runs-on: ubuntu-latest
        timeout-minutes: 10

        strategy:
            matrix:
                python-version: ['3.8', '3.9', '3.10']

        steps:
        -   uses: actions/checkout@v2

        -   name: Cache Python dependencies
            id: cache-pip
            uses: actions/cache@v1
            with:
                path: ~/.cache/pip
                key: pip-${{ matrix.python-version }}-tests-${{ hashFiles('**/setup.json') }}
                restore-keys:
                    pip-${{ matrix.python-version }}-tests

        -   name: Install Python ${{ matrix.python-version }}
            uses: actions/setup-python@v2
            with:
                python-version: ${{ matrix.python-version }}

        -   name: Install Python package and dependencies
            run: pip install -e .[tests]

        -   name: Install custom `aiida-core` branch
            run: pip install git+https://github.com/sphuber/aiida-core.git@feature/5495/storage-backend-entry-points

        -   name: Run pytest
            run: pytest -sv tests
